# Generated by Django 3.0.3 on 2020-04-06 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='experience',
            new_name='recruit_experience',
        ),
    ]
