# Generated by Django 3.0.3 on 2020-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0002_auto_20200406_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document_details',
            name='addr_proof',
            field=models.ImageField(upload_to='documents/pic'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='bank_passbook',
            field=models.ImageField(upload_to='documents/pic'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='photo',
            field=models.ImageField(upload_to='documents/pic'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='resume',
            field=models.FileField(upload_to='documents/pic'),
        ),
        migrations.AlterField(
            model_name='document_details',
            name='signature',
            field=models.ImageField(upload_to='documents/pic'),
        ),
    ]
