# Generated by Django 3.0.3 on 2020-04-07 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0004_auto_20200406_2332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='document_details',
        ),
    ]
