# Generated by Django 3.0.3 on 2020-04-07 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0005_delete_document_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='document_details',
            fields=[
                ('j_id', models.IntegerField(primary_key=True, serialize=False)),
                ('aadhar', models.URLField()),
                ('photo', models.URLField()),
                ('signature', models.URLField()),
                ('resume', models.URLField()),
            ],
        ),
    ]
