# Generated by Django 3.0.3 on 2020-05-17 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Recruit', '0006_document_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='ischedule',
            fields=[
                ('post', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('iDate', models.DateField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
            ],
            options={
                'db_table': 'ischedule',
            },
        ),
    ]
